# Generated by Django 2.2.3 on 2019-07-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_cateogary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateogary',
            name='slug',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
